name: nutrition_tracker
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

workspace:
  - packages/nt_ui
  - packages/food_record_dao
  - packages/food_record_repository

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  food_record_dao: 0.1.0+1
  food_record_repository: 0.1.0+1
  freezed_annotation: ^2.4.1
  go_router: ^15.1.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  nt_ui: 0.1.0+1
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1 

flutter:
  uses-material-design: true
  generate: true
