name: user_measurement_repository
description: User Measurement Repository package for Nutrition Tracker
version: 0.1.0+1
publish_to: none

publish_from_workspace: true

resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  user_measurement_dao: ^0.1.0+1

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^3.0.0-0.0.dev
