name: nt_ui
description: UI package for nutrition tracker
version: 0.1.0+1
publish_to: none

publish_from_workspace: true

resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
