name: food_api_repository
description: A repository for food data from external APIs
version: 0.1.0+1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  nutritionix_api_client: ^0.1.0+1

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.4.7
